service: my-node-app #Unique name for all containers and services                
image: kamal #repo name

builder:
  arch: amd64

servers:
 web:
  hosts:
    - 13.126.175.228
  env:
    APP_ROLE: web
  proxy:
      path_prefix: /
 
 Worker:
  hosts:
    - 13.126.175.228

  env:
    APP_ROLE: worker
  cmd: /app/my-go-app
  proxy: false

ssh:
 user: root
 keys:
      - ~/.ssh/kamal-test-new.pem

proxy:
  host: 13.126.175.228
  app_port: 3000       
  healthcheck:             
    path: /up            
    interval:  1           
    timeout: 3  


registry:
 server: 421600551233.dkr.ecr.ap-south-1.amazonaws.com 
 username: AWS
 password: <%= %x(aws ecr get-login-password --region ap-south-1 --profile rvj-yash) %> 