
require_destination: true

registry:
  server: 495599768662.dkr.ecr.ap-south-1.amazonaws.com
  username: AWS
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: root
  keys:
    - ~/.ssh/soulbol-kamal-ronak.pem

builder:
  arch: amd64